; =============================
; Panloopticon System Variables
; =============================

[Variables]
DynamicWallpapers=1
colorText=000000

[LocationStyle]
StringEffect=Shadow
FibtEffectColor=E56500
FontColor=#colorText#
FontFace=Montserrat Bold
InlineSetting=CharacterSpacing | -1 | -1
FontSize=48
StringCase=Upper
AntiAlias=1

[LocationStyleSub]
StringEffect=Shadow
FibtEffectColor=E56500
FontColor=#colorText#
FontFace=Montserrat Medium
InlineSetting=CharacterSpacing | 4 | 4
FontSize=26
StringCase=Upper
AntiAlias=1

[LocationStyleExtras]
StringEffect=Shadow
StringStyle=Italic
FibtEffectColor=E56500
FontColor=#colorText#
FontFace=Montserrat
InlineSetting=CharacterSpacing | 4 | 4
FontSize=15
StringCase=Upper
AntiAlias=1